inherit_from:
  - 'https://shopify.github.io/ruby-style-guide/rubocop.yml'

require: rubocop-performance

AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - 'vendor/bundle/**/*'

Metrics/MethodLength:
  Enabled: false

Layout/LineLength:
  Enabled: false

Lint/MissingSuper:
  Enabled: false
