inherit_gem:
  rubocop-shopify: rubocop.yml

require:
  - rubocop-performance
  - rubocop-minitest
  - rubocop-rake

AllCops:
  Exclude:
    - 'vendor/bundle/**/*'
    - 'packaging/builds/**/*'

Metrics/MethodLength:
  Enabled: false

Layout/LineLength:
  Enabled: false

Lint/MissingSuper:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/StringLiteralsInInterpolation:
  Enabled: false
