name: theme-check

type: ruby

up:
  - ruby
  - bundler

commands:
  check:
    desc: 'Check a theme'
    syntax:
      argument: file
    run: bundle exec theme-check
  test:
    syntax:
      argument: file
      optional: args...
    run: bundle exec rake test
  style:
    run: bundle exec rake rubocop
  autocorrect:
    run: bundle exec rubocop --auto-correct
  language-server:
    run: bundle exec theme-check-language-server
