name: platformos-check

type: ruby

up:
  - ruby: "3.2.2"
  - bundler

commands:
  check:
    desc: 'Check an pOS app '
    syntax:
      argument: file
    run: bundle exec platformos-check
  test:
    syntax:
      argument: file
      optional: args...
    run: bundle exec rake test
  style:
    run: bundle exec rake rubocop
  autocorrect:
    run: bundle exec rubocop --auto-correct
  language-server:
    run: bundle exec platformos-check-language-server
