#!/usr/bin/env ruby
# frozen_string_literal: true

require 'liquid_language_server'

if ENV["LIQUID_LSP_DEBUG"] == "true"
  $DEBUG = true
end
# Force encoding to UTF-8 to fix VSCode
Encoding.default_external = Encoding::UTF_8
status_code = LiquidLanguageServer::Server.start
exit! status_code
