#!/usr/bin/env ruby
# frozen_string_literal: true

require "theme_check"

path = ARGV[0] || "."
theme = ThemeCheck::Theme.new(path)
if theme.all.empty?
  abort("No templates found.\nusage: theme-check /path/to/your/theme")
end
analyzer = ThemeCheck::Analyzer.new(theme)
analyzer.analyze_theme
ThemeCheck::Printer.new.print(theme, analyzer.offenses)
abort if analyzer.offenses.any?
